### PR TITLE
pvr: fixes for the pvr section

### PR DESCRIPTION
**Pull request by xhaggi**
see commit details

### CODE REVIEW

**Comment by Black09** [comment]
Thanks. So I assume the recording info dialog is the same as the channel info?

**Comment by xhaggi** [comment]
almost the same .. but the endtime is not set

**Comment by Black09** [comment]
Alright. Where do you open the recording info in the osd? Does it happen automatically instead of the channel info?

**Comment by xhaggi** [comment]
you can open the recording info dialog within the recording view .. press key i on one of the recording items .. like you can do on channels

**Comment by Black09** [comment]
Ok

**Pull request merged**
