### PR TITLE
Russian translations

### PR DESCRIPTION
**Pull request by olegstepura**
Hi!

I've made Russian translations for your skin. Thus XPCondensed font doesn't support Cyrillic I had to replace it with similar font from Google Web Fonts repo - Ubuntu Condensed. This new font will let the translation to work and also will enable the usage of the skin for more users who's languages are far beyond latin1 charset (if the font does not support their' language characters the file/movies/songs listings are also lacking those chars)

### CODE REVIEW

**Comment by Black09** [comment]
Hi, I won't add this font to the skin at the moment... I can merge the translation but not the font because I would have to make serveral adjustments (alignment, font size on some labels) if I replace the font (+ I don't like that font as much as Segoe Condensed :))

I'm still searching for a replacement which requires as few changes as possible but I didn't find such a font yet.

**Comment by olegstepura** [comment]
Translations are useless without font support. If it's possible to have Cyrillic support in the original font - that would be perfect, but imho that font is latin1-only

**Comment by olegstepura** [comment]
FYI: I did a quite deep research for the better alternative font supporting Cyrillic symbols and found nothing. But I think I know the solution, I will make separate fontset with Ubuntu Condensed as a default font and that would be the only working solution for Russian.

**Comment by Black09** [comment]
I've found Segoe Condensed with cyrillic chars but I have to adjust y alignment, seems a little bit different... but you could do a quick try -> http://cl.ly/1X1b452e210B3k1F0Y0R

**Comment by olegstepura** [comment]
Cool, confirm that it works for Russian. Is it legal to be used here?

**Comment by Black09** [comment]
Not more or less as the old font. I'll add it soon together with your translation.

**Comment by olegstepura** [comment]
Thanks! I have some other thoughts on improving the skin's usability, do you accept skin-related changes?

The most painful lack of feature for me is the missing of the currently playing song information, and the next one (as in default skin)
Also Volume level editing in the fullscreen mode is done without visual feeling (as db value text only)
Also my current commit has a black stage which is good to have in skin toolbox for usage with different background images (didn't you think of changing it? It looks amazing with backgrounds like this: http://d.pr/QG0f)
And I must notice skin itself uses bad practice for storing selectable settings (predefined stage image - dark - for example) as it saves the localized string in the settings and operates on it, if I change the language I even cannot change it anymore

**Comment by Black09** [comment]
I noticed that with the setting by localized value myself, will see what I can do to fix that issue.

Your screen doesn't have any stage image at all, doesn't it? You can simply set the stage style to custom and set any image you want (no image by default).

Volume level was discussed in the thread, most people preferred the db value as av receivers also display the db value.

Now playing song information isn't that necessary I think, you can open the guide menu to check which song is playing. But if you'll be able to find a very elegant way of integrating full now playing information in the skin, I might reconsider. :)

**Comment by olegstepura** [comment]
Actually it has stage image but not that easy to be recognized on this background. It's visible when playing a song and seeing light fanart image on background or using a lighter image as a background.

The screen I provided was to ask you if you think it is cool or not to change the built-in image's default color theme to more pastel.

I would prefer to have a setting for displaying the volume in db or as a progress image with percentage

Now playing can be easily made as a text in the bottom, see default skin for an example. Current time and the total time of the song is required. And when I do fast forward I expect to see any visual response - default skin shows it's default progress bar in that particular case. So by combing those we can create a great now playing notification.  And it also can be turned on or off via skin settings.

BTW did I tell you your work in general is fantastic. The one and only skin I selected for use after looking at the whle bunch of the skins out there and thus going to make it perfectly fit for me =)

**Comment by olegstepura** [comment]
Please note there is a glitch when tab name is kind of long:  http://d.pr/kWHo  and  http://d.pr/H8gE
Maybe it makes sense making room for it wider.

**Comment by Black09** [comment]
I have fixed the first glitch, don't know why that was happening but the line break in the second screen is hardcoded in the russian language file so nothing I can do about that. I've increased the height of the label so the text doesn't get cut off.

**Comment by olegstepura** [comment]
Hi! I've added an icon for Transmission as it's plugin is the second most used feature after youtube

**Comment by olegstepura** [comment]
Hi! I've merged your modifications for the menu glitch and now it looks even worse: http://d.pr/Wjai As you can see - two different menus appear in 3 visible partly cut lines. This happens now all over the skin even for menu lines with no forced newline ( http://d.pr/cqeH ).

**Comment by Black09** [comment]
Working fine here, only a new line if there's a [CR] in the language file. Which XBMC version do you use?

**Comment by olegstepura** [comment]
git - updated for several weeks ago now

**Comment by Black09** [comment]
Please install the Beta 3.

**Comment by olegstepura** [comment]
This is the screenshot taken from beta 3  under windows http://img4.imageshack.us/img4/2056/screenshot000np.png

**Comment by Black09** [comment]
Forgot to commit a file, should work now.

**Comment by olegstepura** [comment]
Yeah, much better =). Do you mind having transmission icon in the skin? And did you test my stage file?

**Pull request closed without merging**
